Repository Malagor/rsclone, pull requests merged in 2021-02, with the labels that each got.

#144 Bb 57 fix answer button in message
  src/js/Pages/Contacts/Contacts.ts
  src/js/Pages/Contacts/modal.html
  src/js/Pages/Contacts/onClickContactInContactsList.ts
  src/js/Pages/Messenger/Messenger.ts
  src/scss/section/header.scss
Labels: fix

#145 Bb 44 delete group
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Interfaces/IGroupData.ts
  src/js/Pages/MyGroups/MyGroups.ts
  src/js/Pages/MyGroups/myGroups.scss
Labels: feat, fix

#151 feat/fix: delete console statements
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Pages/AuthPage/AuthPage.ts
  src/js/Pages/Contacts/Contacts.ts
  src/js/Pages/Layout/Layout.ts
  src/js/Pages/RegistrationPage/RegistrationPage.ts
  src/js/Pages/TransactionsList/editSum.ts
  src/js/Util/getFormData.ts
Labels: fix

#141 Bb 11 multylanguage main
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Pages/AccountPage/AccountPage.ts
  src/js/Pages/Layout/Layout.ts
  src/js/Pages/Layout/layout.scss
  src/js/Pages/Main/Main.ts
  src/js/Util/saveLoadLanguage.ts
  src/js/languages/ENG/messages.ts
  src/js/languages/RU/messages.ts
Labels: feat, fix

#154 Bb 59 add graph group v2
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Pages/MyGroups/MyGroups.ts
  src/js/Pages/MyGroups/myGroups.scss
  src/js/Pages/TransactionsList/editSum.ts
  src/js/Pages/TransactionsList/renderDetailsHTML.ts
  src/js/Pages/TransactionsList/transactionsList.ts
  src/js/Pages/newTransaction/clearAllInputs.ts
  src/js/Pages/newTransaction/newTransaction.ts
Labels: feat, fix

#150 BB-57 fix edit transaction
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Pages/TransactionsList/renderDetailsHTML.ts
  src/js/Pages/TransactionsList/renderTransCardHTML.ts
  src/js/Pages/TransactionsList/transactionsList.scss
  src/js/Pages/TransactionsList/transactionsList.ts
  src/js/Pages/newTransaction/newTransaction.scss
Labels: fix

#147 Bb 42 help page group
  src/js/Pages/Help/help.html
Labels: feat

#119 Bb 11 multylanguage
  package-lock.json
  package.json
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Pages/AccountPage/AccountPage.ts
  src/js/Pages/AuthPage/AuthPage.ts
  src/js/Pages/Contacts/Contacts.ts
  src/js/Pages/Layout/Layout.ts
  src/js/Pages/Layout/layout.scss
  src/js/Pages/Main/Main.ts
  src/js/Pages/Messenger/Messenger.ts
  src/js/Pages/MyGroups/MyGroups.ts
  src/js/Pages/RegistrationPage/RegistrationPage.ts
  src/js/Pages/TransactionsList/changeBalanceStyle.ts
  src/js/Pages/TransactionsList/getDate.ts
  src/js/Pages/TransactionsList/renderCheckedMember.ts
  src/js/Pages/TransactionsList/renderDetailsHTML.ts
  src/js/Pages/TransactionsList/renderNonCheckedMember.ts
  src/js/Pages/TransactionsList/renderTransCardHTML.ts
  src/js/Pages/TransactionsList/renderTransListHTML.ts
  src/js/Pages/TransactionsList/transactionsList.ts
  src/js/Pages/newTransaction/addMemberHTML.ts
  src/js/Pages/newTransaction/newTransaction.ts
  src/js/Util/saveLoadLanguage.ts
  src/js/languages/ENG/messages.ts
  src/js/languages/RU/messages.ts
Labels: feat

#157 fix: removed the notification when deleting a contact
  src/js/Classes/App.ts
  src/js/Pages/Layout/layout.scss
  src/js/Pages/Main/main.scss
  src/js/Pages/Messenger/messenger.scss
  src/js/Pages/MyGroups/myGroups.scss
  src/js/Pages/TransactionsList/transactionsList.scss
  src/scss/_misc/variables.scss
  src/scss/basic-styles.scss
Labels: fix

#153 refactor: change filename of Classes
  src/js/Classes/App.ts
  src/js/Classes/Modal.ts
  src/js/Classes/User.ts
  src/js/Data/groups.ts
  src/js/Pages/Account/Account.ts
  src/js/Pages/Account/account.scss
  src/js/Pages/Groups/Groups.ts
  src/js/Pages/Groups/groups.scss
  src/js/Pages/NewTransaction/NewTransaction.ts
  src/js/Pages/NewTransaction/addMemberHTML.ts
  src/js/Pages/NewTransaction/checkData.ts
  src/js/Pages/NewTransaction/clearAllInputs.ts
  src/js/Pages/NewTransaction/divideSum.ts
  src/js/Pages/NewTransaction/newTransaction.scss
  src/js/Pages/Registration/Registration.ts
  src/js/Pages/TransactionsList/transactionsList.ts
  src/js/Pages/defaultBlock/defaultBlock.ts
  src/js/Pages/stylePages.ts
Labels: refactor

#158 Bb 61 fix theme
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Pages/Account/account.scss
  src/js/Pages/Layout/Layout.ts
  src/js/Pages/Layout/layout.scss
  src/js/Pages/Main/Main.ts
  src/js/Pages/Main/main.scss
Labels: fix

#160 Bb 60 fix group page
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Pages/Groups/Groups.ts
  src/js/Pages/Groups/groups.scss
  src/js/Pages/TransactionsList/renderTransListHTML.ts
  src/js/languages/ENG/messages.ts
  src/js/languages/RU/messages.ts
  src/scss/_misc/variables.scss
Labels: fix

#162 Bb 62 translation help
  src/js/Classes/App.ts
  src/js/Pages/AuthPage/authPage.scss
  src/js/Pages/Contacts/Contacts.ts
  src/js/Pages/Groups/Groups.ts
  src/js/Pages/Help/Help.scss
  src/js/Pages/Help/Help.ts
  src/js/Pages/Help/help.html
  src/js/Pages/Help/helpHTML.ts
  src/js/Pages/Layout/Layout.ts
  src/js/Pages/Messenger/Messenger.ts
  src/js/Pages/NewTransaction/NewTransaction.ts
  src/js/Pages/NewTransaction/addMemberHTML.ts
  src/js/Pages/Registration/Registration.ts
  src/js/Pages/TransactionsList/renderCheckedMember.ts
  src/js/Pages/TransactionsList/renderDetailsHTML.ts
  src/js/Pages/TransactionsList/renderNonCheckedMember.ts
  src/js/Pages/TransactionsList/renderTransCardHTML.ts
  src/js/Pages/TransactionsList/renderTransListHTML.ts
  src/js/Pages/TransactionsList/transactionsList.ts
  src/js/Pages/stylePages.ts
  src/js/languages/ENG/messages.ts
  src/js/languages/RU/messages.ts
  src/scss/components/_block.scss
Labels: feat, fix

#163 fix: fix translation
  src/js/Pages/Help/helpHTML.ts
  src/js/languages/RU/messages.ts
Labels: fix

#165 Bb 60 fix group page v2
  src/js/Classes/Database.ts
  src/js/Pages/Groups/Groups.ts
  src/js/Pages/Groups/groups.scss
  src/js/Pages/Main/Main.ts
  src/js/languages/ENG/messages.ts
  src/js/languages/RU/messages.ts
Labels: fix

#169 fix: fix graph data
  src/js/Classes/ChartBar.ts
Labels: fix

#170 Bb 60 fix group page v3
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Pages/Groups/Groups.ts
  src/js/Pages/Groups/groups.scss
  src/js/languages/ENG/messages.ts
  src/js/languages/RU/messages.ts
Labels: fix

#173 Bb 65 fix approve group
  src/js/Classes/App.ts
  src/js/Classes/Database.ts
  src/js/Pages/Contacts/Contacts.ts
  src/js/Pages/Groups/Groups.ts
  src/js/Pages/Main/Main.ts
  src/js/languages/RU/messages.ts
Labels: fix, highPriority

#174 fix: change class for contact-user-list
  src/js/Pages/Contacts/Contacts.ts
Labels: fix

#175 fix: fix event bug
  src/js/Classes/ChartBar.ts
Labels: fix

#179 fix: fixed send user info for change user state and render group list
  src/js/Pages/Groups/Groups.ts
Labels: fix
